### PR TITLE
Add Starburst logo in README

### PR DESCRIPTION
**Pull request by damian3031**
New README rendered [here](https://github.com/starburstdata/dbt-trino/blob/add-starburst-logo-in-readme/README.md)

### CODE REVIEW

**Review by hovaesco — APPROVED** [review]

**Comment by mdesmet** [comment]
It doesn't look very well in dark mode:

image

**Comment by leniartek** [comment]
> It doesn't look very well in dark mode:
> 
> image

Good point.
That's why we should use the logo with background.
Starburst_Logo_224x164
Screenshot 2023-03-14 at 14 21 38

**Comment by hovaesco** [comment]
Then it will look bad in light mode.

**Comment by leniartek** [comment]
> Then it will look bad in light mode.

Nooo it will not.
Black background is ok, it's our current branding :)

**Comment by damian3031** [comment]
I changed it so now we have black logo in light mode and white logo in dark mode. WDYT now? I could change Trino and dbt logos to behave the same, if dark mode versions of them are available.

**Comment by damian3031** [comment]
@leniartek @aalbu @hovaesco @mdesmet I've adjusted all logos to light and dark mode, please let me know if it is nice now 🙂 
Screenshot 2023-03-20 at 13 31 54

Screenshot 2023-03-20 at 13 32 17

**Review by leniartek — APPROVED** [review]
Great job, approved!

**Pull request merged**
