### PR TITLE
Bump trino from 0.318.0 to 0.319.0

### PR DESCRIPTION
**Pull request by mederka**

### CODE REVIEW

**Review by hovaesco — APPROVED** [review]

**Comment by hovaesco** [comment]
Just of the curiosity, are you interested in any particular feature of `0.319.0`?

**Comment by mederka** [comment]
Hi there! We're working on supporting dbt-trino in [dbt-fal](https://github.com/fal-ai/fal/tree/main/adapter), so that dbt-trino users can execute Python models. We do this by using sqlalchemy. And it looks like sqlalchemy is broken in 0.318.0, as mentioned [here](https://github.com/trinodb/trino-python-client/issues/286) and [here](https://github.com/trinodb/trino-python-client/issues/273).

**Comment by mederka** [comment]
@hovaesco, is changelog entry necessary here?

**Comment by hovaesco** [comment]
Very cool! @mederka yes, please. The last trino-python-client upgrade missed a changelog entry.

**Comment by mederka** [comment]
Ok, @hovaesco, I think it's ready to merge.

**Comment by chamini2** [comment]
Hi! We were wondering when we could get this released? Is there anything else that needs to be done before 1.3.2?

Thanks for this!

**Comment by hovaesco** [comment]
A plan is to release a new version this week.

**Pull request merged**
