### PR TITLE
Bump Trino to 0.326

### PR DESCRIPTION
**Pull request by Fokko**
## Overview

https://github.com/trinodb/trino-python-client/blob/master/CHANGES.md

## Checklist

- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] `README.md` updated and added information about my change
- [x] I have run `changie new` to [create a changelog entry](https://github.com/starburstdata/dbt-trino/blob/master/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by findinpath** [comment]
Maybe `EXECUTE IMMEDIATE` https://github.com/trinodb/trino-python-client/blob/master/CHANGES.md#release-03250 could be used on `seed`

**Comment by hovaesco** [comment]
> Maybe EXECUTE IMMEDIATE https://github.com/trinodb/trino-python-client/blob/master/CHANGES.md#release-03250 could be used on seed.

it should work out of the box if server supports it (>417).

**Comment by Fokko** [comment]
@hovaesco @findinpath I've got the test passing locally, could we kick off the CI.

**Comment by hovaesco** [comment]
@Fokko please squash the commits and we're good to go!

**Comment by Fokko** [comment]
@hovaesco Done!

**Comment by damian3031** [comment]
@Fokko please rebase onto master, as `test_constraints` tests are already fixed there.

**Comment by Fokko** [comment]
@damian3031 Thanks for the heads-up, done!

**Review by damian3031 — APPROVED** [review]

**Pull request merged**
